#index:
#    path: /
#    controller: App\Controller\DefaultController::index

register:
    path: /users
    controller: App\Controller\UserController::register
    methods: POST

api_login_check:
    path: /api/login_check